# -*- coding: utf-8 -*-
"""CSC101 Week 3 In Class Examples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LRj4NoBFlpuePb9MN9z51FUpcDFZhMIe
"""

## Variables

# Assignment
name = "Alice"  # String
age = 20        # Integer
height = 5.5    # Float

print(name)
print(age)
print(height)

# Python is dynamically typed
name = 7.1      # Float
age = 'young'   # String
height = 60     # Int

print(name)
print(age)
print(height)

"""## Operators"""

print(3 + 4)     # addition
print(10 - 6)    # subtraction
print(12 * 2)    # multiplication
print(35 / 7)    # division
print(35 / 10)   # division
print(35 // 10)  # integer division (floor division)
print(35 % 10)   # modulus (remainder)
print(2**3)      # exponents
print(20 ** 99)  # exponents

"""## Expressions

Expressions are *evaluated*

### Order of Operations
  - Parentheses
  - Exponents
  - Multiplcation / Division
  - Addition / Subtraction

Associativity - Left to Right
Associativity of assignment is Right to Left (right hand side of the equals sign is evaluated before making the assignment)
"""

print(3 + 4 * 2)
print(100 - (2 * 4) ** 2)

# Expressions & assignment
a = 7 * 4 + 30 / 16 - 5
b = 7 * (4 + 30) / (16 - 5)
print(a)
print(b)

"""Input & Output"""

# Get input from a user
answer = input("What's your name? ")
age = int(input("How old are you? "))

print("Hello " + answer)  # combine 2 strings with concatenation
print(f"Hello, {answer}") # an f-string lets you build a string with variables in it
print("Hello", answer, "you are ", age, sep='#')
print(f"Hello, {answer}!  You are {age} years old.")

# Next year
age += 1
print(f"Next year, you will be {age} years old.")

"""## Constants

*or lack thereof*

In Python, constants are a convention, not a feature.  ALL_CAPS indicates a value is a constant and should not be changed.  But Python doesn't enforce that.
"""

# Constants names should all caps
MAX = 100
PI = 3.14159

print(f"Constants: max={MAX}, pi={PI}")

# BUT Python does enforce!!
MAX = 150
PI = 3

print(f"Constants: max={MAX}, pi={PI}")